config:
  auth_server: false
  oauth2:
    check_token_url: http://localhost:9999/uaa/oauth/check_token
    client_id: checkTokenClient
    client_secret: password1

server:
  port: 9998
  contextPath: /api

tokenDatasource:
  mongo-uri: mongodb://tokenstore_user:Password1!@localhost:27017/tokenstoredb_US
  preserve-data: true